package store.entity;
// Generated Jan 3, 2018 7:59:26 PM by Hibernate Tools 4.3.1



/**
 * AktorKonekcija generated by hbm2java
 */
public class AktorKonekcija  implements java.io.Serializable {


     private AktorKonekcijaId id;
     private Aktor aktor;
     private Crtez crtez;
     private UseCase useCase;

    public AktorKonekcija() {
    }

    public AktorKonekcija(AktorKonekcijaId id, Aktor aktor, Crtez crtez, UseCase useCase) {
       this.id = id;
       this.aktor = aktor;
       this.crtez = crtez;
       this.useCase = useCase;
    }
   
    public AktorKonekcijaId getId() {
        return this.id;
    }
    
    public void setId(AktorKonekcijaId id) {
        this.id = id;
    }
    public Aktor getAktor() {
        return this.aktor;
    }
    
    public void setAktor(Aktor aktor) {
        this.aktor = aktor;
    }
    public Crtez getCrtez() {
        return this.crtez;
    }
    
    public void setCrtez(Crtez crtez) {
        this.crtez = crtez;
    }
    public UseCase getUseCase() {
        return this.useCase;
    }
    
    public void setUseCase(UseCase useCase) {
        this.useCase = useCase;
    }




}


