package store.entity;
// Generated Jan 5, 2018 2:02:22 AM by Hibernate Tools 4.3.1



/**
 * AktorKonekcijaDb generated by hbm2java
 */
public class AktorKonekcijaDb  implements java.io.Serializable {


     private AktorKonekcijaDbId id;
     private AktorDb aktorDb;
     private CrtezDb crtezDb;
     private UseCaseDb useCaseDb;

    public AktorKonekcijaDb() {
    }

    public AktorKonekcijaDb(AktorKonekcijaDbId id, AktorDb aktorDb, CrtezDb crtezDb, UseCaseDb useCaseDb) {
       this.id = id;
       this.aktorDb = aktorDb;
       this.crtezDb = crtezDb;
       this.useCaseDb = useCaseDb;
    }
   
    public AktorKonekcijaDbId getId() {
        return this.id;
    }
    
    public void setId(AktorKonekcijaDbId id) {
        this.id = id;
    }
    public AktorDb getAktorDb() {
        return this.aktorDb;
    }
    
    public void setAktorDb(AktorDb aktorDb) {
        this.aktorDb = aktorDb;
    }
    public CrtezDb getCrtezDb() {
        return this.crtezDb;
    }
    
    public void setCrtezDb(CrtezDb crtezDb) {
        this.crtezDb = crtezDb;
    }
    public UseCaseDb getUseCaseDb() {
        return this.useCaseDb;
    }
    
    public void setUseCaseDb(UseCaseDb useCaseDb) {
        this.useCaseDb = useCaseDb;
    }




}


