package store.entity;
// Generated Dec 27, 2017 1:33:44 AM by Hibernate Tools 4.3.1



/**
 * AktorKonekcija generated by hbm2java
 */
public class AktorKonekcija  implements java.io.Serializable {


     private Integer id;
     private Integer crtezId;
     private Integer aktorId;
     private Integer uceCaseId;
     private Integer useCaseKonekcijaId;

    public AktorKonekcija() {
    }

    public AktorKonekcija(Integer crtezId, Integer aktorId, Integer uceCaseId, Integer useCaseKonekcijaId) {
       this.crtezId = crtezId;
       this.aktorId = aktorId;
       this.uceCaseId = uceCaseId;
       this.useCaseKonekcijaId = useCaseKonekcijaId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getCrtezId() {
        return this.crtezId;
    }
    
    public void setCrtezId(Integer crtezId) {
        this.crtezId = crtezId;
    }
    public Integer getAktorId() {
        return this.aktorId;
    }
    
    public void setAktorId(Integer aktorId) {
        this.aktorId = aktorId;
    }
    public Integer getUceCaseId() {
        return this.uceCaseId;
    }
    
    public void setUceCaseId(Integer uceCaseId) {
        this.uceCaseId = uceCaseId;
    }
    public Integer getUseCaseKonekcijaId() {
        return this.useCaseKonekcijaId;
    }
    
    public void setUseCaseKonekcijaId(Integer useCaseKonekcijaId) {
        this.useCaseKonekcijaId = useCaseKonekcijaId;
    }




}


