package store.entity;
// Generated Jan 5, 2018 2:02:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AktorDb generated by hbm2java
 */
public class AktorDb  implements java.io.Serializable {


     private AktorDbId id;
     private CrtezDb crtezDb;
     private String naziv;
     private Double pocetnaKoorX;
     private Double pocetnaKoorY;
     private Double visina;
     private Double sirina;
     private Set aktorKonekcijaDbs = new HashSet(0);

    public AktorDb() {
    }

	
    public AktorDb(AktorDbId id, CrtezDb crtezDb) {
        this.id = id;
        this.crtezDb = crtezDb;
    }
    public AktorDb(AktorDbId id, CrtezDb crtezDb, String naziv, Double pocetnaKoorX, Double pocetnaKoorY, Double visina, Double sirina, Set aktorKonekcijaDbs) {
       this.id = id;
       this.crtezDb = crtezDb;
       this.naziv = naziv;
       this.pocetnaKoorX = pocetnaKoorX;
       this.pocetnaKoorY = pocetnaKoorY;
       this.visina = visina;
       this.sirina = sirina;
       this.aktorKonekcijaDbs = aktorKonekcijaDbs;
    }
   
    public AktorDbId getId() {
        return this.id;
    }
    
    public void setId(AktorDbId id) {
        this.id = id;
    }
    public CrtezDb getCrtezDb() {
        return this.crtezDb;
    }
    
    public void setCrtezDb(CrtezDb crtezDb) {
        this.crtezDb = crtezDb;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Double getPocetnaKoorX() {
        return this.pocetnaKoorX;
    }
    
    public void setPocetnaKoorX(Double pocetnaKoorX) {
        this.pocetnaKoorX = pocetnaKoorX;
    }
    public Double getPocetnaKoorY() {
        return this.pocetnaKoorY;
    }
    
    public void setPocetnaKoorY(Double pocetnaKoorY) {
        this.pocetnaKoorY = pocetnaKoorY;
    }
    public Double getVisina() {
        return this.visina;
    }
    
    public void setVisina(Double visina) {
        this.visina = visina;
    }
    public Double getSirina() {
        return this.sirina;
    }
    
    public void setSirina(Double sirina) {
        this.sirina = sirina;
    }
    public Set getAktorKonekcijaDbs() {
        return this.aktorKonekcijaDbs;
    }
    
    public void setAktorKonekcijaDbs(Set aktorKonekcijaDbs) {
        this.aktorKonekcijaDbs = aktorKonekcijaDbs;
    }




}


