package store.entity;
// Generated Jan 3, 2018 7:59:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aktor generated by hbm2java
 */
public class Aktor  implements java.io.Serializable {


     private AktorId id;
     private Crtez crtez;
     private String naziv;
     private Double pocetnaKoorX;
     private Double pocetnaKoorY;
     private Double visina;
     private Double sirina;
     private Set aktorKonekcijas = new HashSet(0);

    public Aktor() {
    }

	
    public Aktor(AktorId id, Crtez crtez) {
        this.id = id;
        this.crtez = crtez;
    }
    public Aktor(AktorId id, Crtez crtez, String naziv, Double pocetnaKoorX, Double pocetnaKoorY, Double visina, Double sirina, Set aktorKonekcijas) {
       this.id = id;
       this.crtez = crtez;
       this.naziv = naziv;
       this.pocetnaKoorX = pocetnaKoorX;
       this.pocetnaKoorY = pocetnaKoorY;
       this.visina = visina;
       this.sirina = sirina;
       this.aktorKonekcijas = aktorKonekcijas;
    }
   
    public AktorId getId() {
        return this.id;
    }
    
    public void setId(AktorId id) {
        this.id = id;
    }
    public Crtez getCrtez() {
        return this.crtez;
    }
    
    public void setCrtez(Crtez crtez) {
        this.crtez = crtez;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Double getPocetnaKoorX() {
        return this.pocetnaKoorX;
    }
    
    public void setPocetnaKoorX(Double pocetnaKoorX) {
        this.pocetnaKoorX = pocetnaKoorX;
    }
    public Double getPocetnaKoorY() {
        return this.pocetnaKoorY;
    }
    
    public void setPocetnaKoorY(Double pocetnaKoorY) {
        this.pocetnaKoorY = pocetnaKoorY;
    }
    public Double getVisina() {
        return this.visina;
    }
    
    public void setVisina(Double visina) {
        this.visina = visina;
    }
    public Double getSirina() {
        return this.sirina;
    }
    
    public void setSirina(Double sirina) {
        this.sirina = sirina;
    }
    public Set getAktorKonekcijas() {
        return this.aktorKonekcijas;
    }
    
    public void setAktorKonekcijas(Set aktorKonekcijas) {
        this.aktorKonekcijas = aktorKonekcijas;
    }




}


