package store.entity;
// Generated Jan 9, 2018 4:38:35 PM by Hibernate Tools 4.3.1



/**
 * ArgumentDb generated by hbm2java
 */
public class ArgumentDb  implements java.io.Serializable {


     private ArgumentDbId id;
     private MetodDb metodDb;
     private String naziv;
     private String tip;

    public ArgumentDb() {
    }

	
    public ArgumentDb(ArgumentDbId id, MetodDb metodDb) {
        this.id = id;
        this.metodDb = metodDb;
    }
    public ArgumentDb(ArgumentDbId id, MetodDb metodDb, String naziv, String tip) {
       this.id = id;
       this.metodDb = metodDb;
       this.naziv = naziv;
       this.tip = tip;
    }
   
    public ArgumentDbId getId() {
        return this.id;
    }
    
    public void setId(ArgumentDbId id) {
        this.id = id;
    }
    public MetodDb getMetodDb() {
        return this.metodDb;
    }
    
    public void setMetodDb(MetodDb metodDb) {
        this.metodDb = metodDb;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }




}


