package store.entity;
// Generated Jan 3, 2018 7:59:26 PM by Hibernate Tools 4.3.1



/**
 * ArgumentId generated by hbm2java
 */
public class ArgumentId  implements java.io.Serializable {


     private int crtezId;
     private int klasaId;
     private int metodId;

    public ArgumentId() {
    }

    public ArgumentId(int crtezId, int klasaId, int metodId) {
       this.crtezId = crtezId;
       this.klasaId = klasaId;
       this.metodId = metodId;
    }
   
    public int getCrtezId() {
        return this.crtezId;
    }
    
    public void setCrtezId(int crtezId) {
        this.crtezId = crtezId;
    }
    public int getKlasaId() {
        return this.klasaId;
    }
    
    public void setKlasaId(int klasaId) {
        this.klasaId = klasaId;
    }
    public int getMetodId() {
        return this.metodId;
    }
    
    public void setMetodId(int metodId) {
        this.metodId = metodId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArgumentId) ) return false;
		 ArgumentId castOther = ( ArgumentId ) other; 
         
		 return (this.getCrtezId()==castOther.getCrtezId())
 && (this.getKlasaId()==castOther.getKlasaId())
 && (this.getMetodId()==castOther.getMetodId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCrtezId();
         result = 37 * result + this.getKlasaId();
         result = 37 * result + this.getMetodId();
         return result;
   }   


}


