package store.entity;
// Generated Jan 5, 2018 2:02:22 AM by Hibernate Tools 4.3.1



/**
 * ArgumentDbId generated by hbm2java
 */
public class ArgumentDbId  implements java.io.Serializable {


     private int crtezId;
     private int klasaId;
     private int metodId;
     private int id;

    public ArgumentDbId() {
    }

    public ArgumentDbId(int crtezId, int klasaId, int metodId, int id) {
       this.crtezId = crtezId;
       this.klasaId = klasaId;
       this.metodId = metodId;
       this.id = id;
    }
   
    public int getCrtezId() {
        return this.crtezId;
    }
    
    public void setCrtezId(int crtezId) {
        this.crtezId = crtezId;
    }
    public int getKlasaId() {
        return this.klasaId;
    }
    
    public void setKlasaId(int klasaId) {
        this.klasaId = klasaId;
    }
    public int getMetodId() {
        return this.metodId;
    }
    
    public void setMetodId(int metodId) {
        this.metodId = metodId;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArgumentDbId) ) return false;
		 ArgumentDbId castOther = ( ArgumentDbId ) other; 
         
		 return (this.getCrtezId()==castOther.getCrtezId())
 && (this.getKlasaId()==castOther.getKlasaId())
 && (this.getMetodId()==castOther.getMetodId())
 && (this.getId()==castOther.getId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCrtezId();
         result = 37 * result + this.getKlasaId();
         result = 37 * result + this.getMetodId();
         result = 37 * result + this.getId();
         return result;
   }   


}


