package store.entity;
// Generated Jan 9, 2018 4:38:35 PM by Hibernate Tools 4.3.1



/**
 * AtributDb generated by hbm2java
 */
public class AtributDb  implements java.io.Serializable {


     private AtributDbId id;
     private KlasaDb klasaDb;
     private String naziv;
     private String tip;
     private String vidljivost;
     private Byte isStatic;

    public AtributDb() {
    }

	
    public AtributDb(AtributDbId id, KlasaDb klasaDb) {
        this.id = id;
        this.klasaDb = klasaDb;
    }
    public AtributDb(AtributDbId id, KlasaDb klasaDb, String naziv, String tip, String vidljivost, Byte isStatic) {
       this.id = id;
       this.klasaDb = klasaDb;
       this.naziv = naziv;
       this.tip = tip;
       this.vidljivost = vidljivost;
       this.isStatic = isStatic;
    }
   
    public AtributDbId getId() {
        return this.id;
    }
    
    public void setId(AtributDbId id) {
        this.id = id;
    }
    public KlasaDb getKlasaDb() {
        return this.klasaDb;
    }
    
    public void setKlasaDb(KlasaDb klasaDb) {
        this.klasaDb = klasaDb;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }
    public String getVidljivost() {
        return this.vidljivost;
    }
    
    public void setVidljivost(String vidljivost) {
        this.vidljivost = vidljivost;
    }
    public Byte getIsStatic() {
        return this.isStatic;
    }
    
    public void setIsStatic(Byte isStatic) {
        this.isStatic = isStatic;
    }




}


