package store.entity;
// Generated Jan 5, 2018 2:02:22 AM by Hibernate Tools 4.3.1



/**
 * AtributDbId generated by hbm2java
 */
public class AtributDbId  implements java.io.Serializable {


     private int crtezId;
     private int klasaId;
     private int attributId;

    public AtributDbId() {
    }

    public AtributDbId(int crtezId, int klasaId, int attributId) {
       this.crtezId = crtezId;
       this.klasaId = klasaId;
       this.attributId = attributId;
    }
   
    public int getCrtezId() {
        return this.crtezId;
    }
    
    public void setCrtezId(int crtezId) {
        this.crtezId = crtezId;
    }
    public int getKlasaId() {
        return this.klasaId;
    }
    
    public void setKlasaId(int klasaId) {
        this.klasaId = klasaId;
    }
    public int getAttributId() {
        return this.attributId;
    }
    
    public void setAttributId(int attributId) {
        this.attributId = attributId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AtributDbId) ) return false;
		 AtributDbId castOther = ( AtributDbId ) other; 
         
		 return (this.getCrtezId()==castOther.getCrtezId())
 && (this.getKlasaId()==castOther.getKlasaId())
 && (this.getAttributId()==castOther.getAttributId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCrtezId();
         result = 37 * result + this.getKlasaId();
         result = 37 * result + this.getAttributId();
         return result;
   }   


}


