package store.entity;
// Generated Jan 9, 2018 4:38:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CrtezDb generated by hbm2java
 */
public class CrtezDb  implements java.io.Serializable {


     private int id;
     private KorisnikDb korisnikDb;
     private String naslov;
     private String tip;
     private Integer counter1;//za klase
     private Integer counter2;//za veze
     private Set dijagramKonekcijaDbs = new HashSet(0);
     private Set interfejsDbs = new HashSet(0);
     private Set klasaDbs = new HashSet(0);
     private Set useCaseKonekcijaDbs = new HashSet(0);
     private Set aktorDbs = new HashSet(0);
     private Set aktorKonekcijaDbs = new HashSet(0);
     private Set korisnikDbs = new HashSet(0);
     private Set useCaseDbs = new HashSet(0);

    public CrtezDb() {
    }

	
    public CrtezDb(int id) {
        this.id = id;
    }
    public CrtezDb(int id, KorisnikDb korisnikDb, String naslov, String tip, Integer counter1, Integer counter2, Set dijagramKonekcijaDbs, Set interfejsDbs, Set klasaDbs, Set useCaseKonekcijaDbs, Set aktorDbs, Set aktorKonekcijaDbs, Set korisnikDbs, Set useCaseDbs) {
       this.id = id;
       this.korisnikDb = korisnikDb;
       this.naslov = naslov;
       this.tip = tip;
       this.counter1 = counter1;
       this.counter2 = counter2;
       this.dijagramKonekcijaDbs = dijagramKonekcijaDbs;
       this.interfejsDbs = interfejsDbs;
       this.klasaDbs = klasaDbs;
       this.useCaseKonekcijaDbs = useCaseKonekcijaDbs;
       this.aktorDbs = aktorDbs;
       this.aktorKonekcijaDbs = aktorKonekcijaDbs;
       this.korisnikDbs = korisnikDbs;
       this.useCaseDbs = useCaseDbs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public KorisnikDb getKorisnikDb() {
        return this.korisnikDb;
    }
    
    public void setKorisnikDb(KorisnikDb korisnikDb) {
        this.korisnikDb = korisnikDb;
    }
    public String getNaslov() {
        return this.naslov;
    }
    
    public void setNaslov(String naslov) {
        this.naslov = naslov;
    }
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }
    public Integer getCounter1() {
        return this.counter1;
    }
    
    public void setCounter1(Integer counter1) {
        this.counter1 = counter1;
    }
    public Integer getCounter2() {
        return this.counter2;
    }
    
    public void setCounter2(Integer counter2) {
        this.counter2 = counter2;
    }
    public Set getDijagramKonekcijaDbs() {
        return this.dijagramKonekcijaDbs;
    }
    
    public void setDijagramKonekcijaDbs(Set dijagramKonekcijaDbs) {
        this.dijagramKonekcijaDbs = dijagramKonekcijaDbs;
    }
    public Set getInterfejsDbs() {
        return this.interfejsDbs;
    }
    
    public void setInterfejsDbs(Set interfejsDbs) {
        this.interfejsDbs = interfejsDbs;
    }
    public Set getKlasaDbs() {
        return this.klasaDbs;
    }
    
    public void setKlasaDbs(Set klasaDbs) {
        this.klasaDbs = klasaDbs;
    }
    public Set getUseCaseKonekcijaDbs() {
        return this.useCaseKonekcijaDbs;
    }
    
    public void setUseCaseKonekcijaDbs(Set useCaseKonekcijaDbs) {
        this.useCaseKonekcijaDbs = useCaseKonekcijaDbs;
    }
    public Set getAktorDbs() {
        return this.aktorDbs;
    }
    
    public void setAktorDbs(Set aktorDbs) {
        this.aktorDbs = aktorDbs;
    }
    public Set getAktorKonekcijaDbs() {
        return this.aktorKonekcijaDbs;
    }
    
    public void setAktorKonekcijaDbs(Set aktorKonekcijaDbs) {
        this.aktorKonekcijaDbs = aktorKonekcijaDbs;
    }
    public Set getKorisnikDbs() {
        return this.korisnikDbs;
    }
    
    public void setKorisnikDbs(Set korisnikDbs) {
        this.korisnikDbs = korisnikDbs;
    }
    public Set getUseCaseDbs() {
        return this.useCaseDbs;
    }
    
    public void setUseCaseDbs(Set useCaseDbs) {
        this.useCaseDbs = useCaseDbs;
    }




}


