package store.entity;
// Generated Jan 9, 2018 4:38:35 PM by Hibernate Tools 4.3.1



/**
 * DijagramKonekcijaDb generated by hbm2java
 */
public class DijagramKonekcijaDb  implements java.io.Serializable {


     private DijagramKonekcijaDbId id;
     private CrtezDb crtezDb;
     private String tipVeze;
     private Integer odKogaId;
     private String odKogaTip;
     private Integer doKogaId;
     private String doKogaTip;

    public DijagramKonekcijaDb() {
    }

	
    public DijagramKonekcijaDb(DijagramKonekcijaDbId id, CrtezDb crtezDb) {
        this.id = id;
        this.crtezDb = crtezDb;
    }
    public DijagramKonekcijaDb(DijagramKonekcijaDbId id, CrtezDb crtezDb, String tipVeze, Integer odKogaId, Integer doKogaId) {
       this.id = id;
       this.crtezDb = crtezDb;
       this.tipVeze = tipVeze;
       this.odKogaId = odKogaId;
       this.doKogaId = doKogaId;
    }
   
    public DijagramKonekcijaDbId getId() {
        return this.id;
    }
    
    public void setId(DijagramKonekcijaDbId id) {
        this.id = id;
    }
    public CrtezDb getCrtezDb() {
        return this.crtezDb;
    }
    
    public void setCrtezDb(CrtezDb crtezDb) {
        this.crtezDb = crtezDb;
    }
    public String getTipVeze() {
        return this.tipVeze;
    }
    
    public void setTipVeze(String tipVeze) {
        this.tipVeze = tipVeze;
    }
    public Integer getOdKogaId() {
        return this.odKogaId;
    }
    
    public void setOdKogaId(Integer odKogaId) {
        this.odKogaId = odKogaId;
    }
    public Integer getDoKogaId() {
        return this.doKogaId;
    }
    
    public void setDoKogaId(Integer doKogaId) {
        this.doKogaId = doKogaId;
    }

    /**
     * @return the odKogaTip
     */
    public String getOdKogaTip() {
        return odKogaTip;
    }

    /**
     * @param odKogaTip the odKogaTip to set
     */
    public void setOdKogaTip(String odKogaTip) {
        this.odKogaTip = odKogaTip;
    }

    /**
     * @return the doKogaTip
     */
    public String getDoKogaTip() {
        return doKogaTip;
    }

    /**
     * @param doKogaTip the doKogaTip to set
     */
    public void setDoKogaTip(String doKogaTip) {
        this.doKogaTip = doKogaTip;
    }




}


