package store.entity;
// Generated Jan 2, 2018 5:10:25 PM by Hibernate Tools 4.3.1



/**
 * DijagramKonekcija generated by hbm2java
 */
public class DijagramKonekcija  implements java.io.Serializable {


     private DijagramKonekcijaId id;
     private Crtez crtez;
     private String tipVeze;
     private Integer odKogaId;
     private Integer doKogaId;

    public DijagramKonekcija() {
    }

	
    public DijagramKonekcija(DijagramKonekcijaId id, Crtez crtez) {
        this.id = id;
        this.crtez = crtez;
    }
    public DijagramKonekcija(DijagramKonekcijaId id, Crtez crtez, String tipVeze, Integer odKogaId, Integer doKogaId) {
       this.id = id;
       this.crtez = crtez;
       this.tipVeze = tipVeze;
       this.odKogaId = odKogaId;
       this.doKogaId = doKogaId;
    }
   
    public DijagramKonekcijaId getId() {
        return this.id;
    }
    
    public void setId(DijagramKonekcijaId id) {
        this.id = id;
    }
    public Crtez getCrtez() {
        return this.crtez;
    }
    
    public void setCrtez(Crtez crtez) {
        this.crtez = crtez;
    }
    public String getTipVeze() {
        return this.tipVeze;
    }
    
    public void setTipVeze(String tipVeze) {
        this.tipVeze = tipVeze;
    }
    public Integer getOdKogaId() {
        return this.odKogaId;
    }
    
    public void setOdKogaId(Integer odKogaId) {
        this.odKogaId = odKogaId;
    }
    public Integer getDoKogaId() {
        return this.doKogaId;
    }
    
    public void setDoKogaId(Integer doKogaId) {
        this.doKogaId = doKogaId;
    }




}


