package store.entity;
// Generated Dec 27, 2017 1:33:44 AM by Hibernate Tools 4.3.1



/**
 * DijagramKonekcija generated by hbm2java
 */
public class DijagramKonekcija  implements java.io.Serializable {


     private DijagramKonekcijaId id;
     private String tipVeze;
     private Integer odKogaId;
     private Integer doKogaId;

    public DijagramKonekcija() {
    }

	
    public DijagramKonekcija(DijagramKonekcijaId id) {
        this.id = id;
    }
    public DijagramKonekcija(DijagramKonekcijaId id, String tipVeze, Integer odKogaId, Integer doKogaId) {
       this.id = id;
       this.tipVeze = tipVeze;
       this.odKogaId = odKogaId;
       this.doKogaId = doKogaId;
    }
   
    public DijagramKonekcijaId getId() {
        return this.id;
    }
    
    public void setId(DijagramKonekcijaId id) {
        this.id = id;
    }
    public String getTipVeze() {
        return this.tipVeze;
    }
    
    public void setTipVeze(String tipVeze) {
        this.tipVeze = tipVeze;
    }
    public Integer getOdKogaId() {
        return this.odKogaId;
    }
    
    public void setOdKogaId(Integer odKogaId) {
        this.odKogaId = odKogaId;
    }
    public Integer getDoKogaId() {
        return this.doKogaId;
    }
    
    public void setDoKogaId(Integer doKogaId) {
        this.doKogaId = doKogaId;
    }




}


