package store.entity;
// Generated Jan 3, 2018 7:59:26 PM by Hibernate Tools 4.3.1



/**
 * DijagramKonekcija generated by hbm2java
 */
public class DijagramKonekcija  implements java.io.Serializable {


     private DijagramKonekcijaId id;
     private Crtez crtez;
     private Interfejs interfejs;
     private Klasa klasaByKonekcijaKlasaFkDoKoga;
     private Klasa klasaByKonekcijaKlasaFkOdKoga;
     private String tipVeze;

    public DijagramKonekcija() {
    }

	
    public DijagramKonekcija(DijagramKonekcijaId id, Crtez crtez, Interfejs interfejs, Klasa klasaByKonekcijaKlasaFkDoKoga, Klasa klasaByKonekcijaKlasaFkOdKoga) {
        this.id = id;
        this.crtez = crtez;
        this.interfejs = interfejs;
        this.klasaByKonekcijaKlasaFkDoKoga = klasaByKonekcijaKlasaFkDoKoga;
        this.klasaByKonekcijaKlasaFkOdKoga = klasaByKonekcijaKlasaFkOdKoga;
    }
    public DijagramKonekcija(DijagramKonekcijaId id, Crtez crtez, Interfejs interfejs, Klasa klasaByKonekcijaKlasaFkDoKoga, Klasa klasaByKonekcijaKlasaFkOdKoga, String tipVeze) {
       this.id = id;
       this.crtez = crtez;
       this.interfejs = interfejs;
       this.klasaByKonekcijaKlasaFkDoKoga = klasaByKonekcijaKlasaFkDoKoga;
       this.klasaByKonekcijaKlasaFkOdKoga = klasaByKonekcijaKlasaFkOdKoga;
       this.tipVeze = tipVeze;
    }
   
    public DijagramKonekcijaId getId() {
        return this.id;
    }
    
    public void setId(DijagramKonekcijaId id) {
        this.id = id;
    }
    public Crtez getCrtez() {
        return this.crtez;
    }
    
    public void setCrtez(Crtez crtez) {
        this.crtez = crtez;
    }
    public Interfejs getInterfejs() {
        return this.interfejs;
    }
    
    public void setInterfejs(Interfejs interfejs) {
        this.interfejs = interfejs;
    }
    public Klasa getKlasaByKonekcijaKlasaFkDoKoga() {
        return this.klasaByKonekcijaKlasaFkDoKoga;
    }
    
    public void setKlasaByKonekcijaKlasaFkDoKoga(Klasa klasaByKonekcijaKlasaFkDoKoga) {
        this.klasaByKonekcijaKlasaFkDoKoga = klasaByKonekcijaKlasaFkDoKoga;
    }
    public Klasa getKlasaByKonekcijaKlasaFkOdKoga() {
        return this.klasaByKonekcijaKlasaFkOdKoga;
    }
    
    public void setKlasaByKonekcijaKlasaFkOdKoga(Klasa klasaByKonekcijaKlasaFkOdKoga) {
        this.klasaByKonekcijaKlasaFkOdKoga = klasaByKonekcijaKlasaFkOdKoga;
    }
    public String getTipVeze() {
        return this.tipVeze;
    }
    
    public void setTipVeze(String tipVeze) {
        this.tipVeze = tipVeze;
    }




}


