package store.entity;
// Generated Jan 5, 2018 2:02:22 AM by Hibernate Tools 4.3.1



/**
 * InterfejsDbId generated by hbm2java
 */
public class InterfejsDbId  implements java.io.Serializable {


     private int crtezId;
     private int interfejsId;

    public InterfejsDbId() {
    }

    public InterfejsDbId(int crtezId, int interfejsId) {
       this.crtezId = crtezId;
       this.interfejsId = interfejsId;
    }
   
    public int getCrtezId() {
        return this.crtezId;
    }
    
    public void setCrtezId(int crtezId) {
        this.crtezId = crtezId;
    }
    public int getInterfejsId() {
        return this.interfejsId;
    }
    
    public void setInterfejsId(int interfejsId) {
        this.interfejsId = interfejsId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InterfejsDbId) ) return false;
		 InterfejsDbId castOther = ( InterfejsDbId ) other; 
         
		 return (this.getCrtezId()==castOther.getCrtezId())
 && (this.getInterfejsId()==castOther.getInterfejsId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCrtezId();
         result = 37 * result + this.getInterfejsId();
         return result;
   }   


}


