package store.entity;
// Generated Jan 3, 2018 7:59:26 PM by Hibernate Tools 4.3.1



/**
 * InterfejsId generated by hbm2java
 */
public class InterfejsId  implements java.io.Serializable {


     private int crtezId;
     private int interfejsId;

    public InterfejsId() {
    }

    public InterfejsId(int crtezId, int interfejsId) {
       this.crtezId = crtezId;
       this.interfejsId = interfejsId;
    }
   
    public int getCrtezId() {
        return this.crtezId;
    }
    
    public void setCrtezId(int crtezId) {
        this.crtezId = crtezId;
    }
    public int getInterfejsId() {
        return this.interfejsId;
    }
    
    public void setInterfejsId(int interfejsId) {
        this.interfejsId = interfejsId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InterfejsId) ) return false;
		 InterfejsId castOther = ( InterfejsId ) other; 
         
		 return (this.getCrtezId()==castOther.getCrtezId())
 && (this.getInterfejsId()==castOther.getInterfejsId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCrtezId();
         result = 37 * result + this.getInterfejsId();
         return result;
   }   


}


