package store.entity;
// Generated Jan 3, 2018 7:59:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Interfejs generated by hbm2java
 */
public class Interfejs  implements java.io.Serializable {


     private InterfejsId id;
     private Crtez crtez;
     private String naziv;
     private Integer metodCounter;
     private Set metods = new HashSet(0);
     private Set dijagramKonekcijas = new HashSet(0);

    public Interfejs() {
    }

	
    public Interfejs(InterfejsId id, Crtez crtez) {
        this.id = id;
        this.crtez = crtez;
    }
    public Interfejs(InterfejsId id, Crtez crtez, String naziv, Integer metodCounter, Set metods, Set dijagramKonekcijas) {
       this.id = id;
       this.crtez = crtez;
       this.naziv = naziv;
       this.metodCounter = metodCounter;
       this.metods = metods;
       this.dijagramKonekcijas = dijagramKonekcijas;
    }
   
    public InterfejsId getId() {
        return this.id;
    }
    
    public void setId(InterfejsId id) {
        this.id = id;
    }
    public Crtez getCrtez() {
        return this.crtez;
    }
    
    public void setCrtez(Crtez crtez) {
        this.crtez = crtez;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Integer getMetodCounter() {
        return this.metodCounter;
    }
    
    public void setMetodCounter(Integer metodCounter) {
        this.metodCounter = metodCounter;
    }
    public Set getMetods() {
        return this.metods;
    }
    
    public void setMetods(Set metods) {
        this.metods = metods;
    }
    public Set getDijagramKonekcijas() {
        return this.dijagramKonekcijas;
    }
    
    public void setDijagramKonekcijas(Set dijagramKonekcijas) {
        this.dijagramKonekcijas = dijagramKonekcijas;
    }




}


