package store.entity;
// Generated Dec 27, 2017 1:33:44 AM by Hibernate Tools 4.3.1



/**
 * Interfejs generated by hbm2java
 */
public class Interfejs  implements java.io.Serializable {


     private InterfejsId id;
     private String naziv;
     private String metoda;

    public Interfejs() {
    }

	
    public Interfejs(InterfejsId id) {
        this.id = id;
    }
    public Interfejs(InterfejsId id, String naziv, String metoda) {
       this.id = id;
       this.naziv = naziv;
       this.metoda = metoda;
    }
   
    public InterfejsId getId() {
        return this.id;
    }
    
    public void setId(InterfejsId id) {
        this.id = id;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getMetoda() {
        return this.metoda;
    }
    
    public void setMetoda(String metoda) {
        this.metoda = metoda;
    }




}


