package store.entity;
// Generated Dec 27, 2017 1:33:44 AM by Hibernate Tools 4.3.1



/**
 * Klasnid generated by hbm2java
 */
public class Klasnid  implements java.io.Serializable {


     private KlasnidId id;
     private String atribut;
     private String metoda;

    public Klasnid() {
    }

	
    public Klasnid(KlasnidId id) {
        this.id = id;
    }
    public Klasnid(KlasnidId id, String atribut, String metoda) {
       this.id = id;
       this.atribut = atribut;
       this.metoda = metoda;
    }
   
    public KlasnidId getId() {
        return this.id;
    }
    
    public void setId(KlasnidId id) {
        this.id = id;
    }
    public String getAtribut() {
        return this.atribut;
    }
    
    public void setAtribut(String atribut) {
        this.atribut = atribut;
    }
    public String getMetoda() {
        return this.metoda;
    }
    
    public void setMetoda(String metoda) {
        this.metoda = metoda;
    }




}


