package store.entity;
// Generated Jan 3, 2018 7:59:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Klasa generated by hbm2java
 */
public class Klasa  implements java.io.Serializable {


     private KlasaId id;
     private Crtez crtez;
     private Integer atributCounter;
     private Integer metodCounter;
     private Byte isAbstract;
     private Byte isStatic;
     private Set metods = new HashSet(0);
     private Set atributs = new HashSet(0);
     private Set dijagramKonekcijasForKonekcijaKlasaFkDoKoga = new HashSet(0);
     private Set dijagramKonekcijasForKonekcijaKlasaFkOdKoga = new HashSet(0);

    public Klasa() {
    }

	
    public Klasa(KlasaId id, Crtez crtez) {
        this.id = id;
        this.crtez = crtez;
    }
    public Klasa(KlasaId id, Crtez crtez, Integer atributCounter, Integer metodCounter, Byte isAbstract, Byte isStatic, Set metods, Set atributs, Set dijagramKonekcijasForKonekcijaKlasaFkDoKoga, Set dijagramKonekcijasForKonekcijaKlasaFkOdKoga) {
       this.id = id;
       this.crtez = crtez;
       this.atributCounter = atributCounter;
       this.metodCounter = metodCounter;
       this.isAbstract = isAbstract;
       this.isStatic = isStatic;
       this.metods = metods;
       this.atributs = atributs;
       this.dijagramKonekcijasForKonekcijaKlasaFkDoKoga = dijagramKonekcijasForKonekcijaKlasaFkDoKoga;
       this.dijagramKonekcijasForKonekcijaKlasaFkOdKoga = dijagramKonekcijasForKonekcijaKlasaFkOdKoga;
    }
   
    public KlasaId getId() {
        return this.id;
    }
    
    public void setId(KlasaId id) {
        this.id = id;
    }
    public Crtez getCrtez() {
        return this.crtez;
    }
    
    public void setCrtez(Crtez crtez) {
        this.crtez = crtez;
    }
    public Integer getAtributCounter() {
        return this.atributCounter;
    }
    
    public void setAtributCounter(Integer atributCounter) {
        this.atributCounter = atributCounter;
    }
    public Integer getMetodCounter() {
        return this.metodCounter;
    }
    
    public void setMetodCounter(Integer metodCounter) {
        this.metodCounter = metodCounter;
    }
    public Byte getIsAbstract() {
        return this.isAbstract;
    }
    
    public void setIsAbstract(Byte isAbstract) {
        this.isAbstract = isAbstract;
    }
    public Byte getIsStatic() {
        return this.isStatic;
    }
    
    public void setIsStatic(Byte isStatic) {
        this.isStatic = isStatic;
    }
    public Set getMetods() {
        return this.metods;
    }
    
    public void setMetods(Set metods) {
        this.metods = metods;
    }
    public Set getAtributs() {
        return this.atributs;
    }
    
    public void setAtributs(Set atributs) {
        this.atributs = atributs;
    }
    public Set getDijagramKonekcijasForKonekcijaKlasaFkDoKoga() {
        return this.dijagramKonekcijasForKonekcijaKlasaFkDoKoga;
    }
    
    public void setDijagramKonekcijasForKonekcijaKlasaFkDoKoga(Set dijagramKonekcijasForKonekcijaKlasaFkDoKoga) {
        this.dijagramKonekcijasForKonekcijaKlasaFkDoKoga = dijagramKonekcijasForKonekcijaKlasaFkDoKoga;
    }
    public Set getDijagramKonekcijasForKonekcijaKlasaFkOdKoga() {
        return this.dijagramKonekcijasForKonekcijaKlasaFkOdKoga;
    }
    
    public void setDijagramKonekcijasForKonekcijaKlasaFkOdKoga(Set dijagramKonekcijasForKonekcijaKlasaFkOdKoga) {
        this.dijagramKonekcijasForKonekcijaKlasaFkOdKoga = dijagramKonekcijasForKonekcijaKlasaFkOdKoga;
    }




}


