package store.entity;
// Generated Dec 27, 2017 1:33:44 AM by Hibernate Tools 4.3.1



/**
 * KlasnidId generated by hbm2java
 */
public class KlasnidId  implements java.io.Serializable {


     private int crtezId;
     private int klasaId;

    public KlasnidId() {
    }

    public KlasnidId(int crtezId, int klasaId) {
       this.crtezId = crtezId;
       this.klasaId = klasaId;
    }
   
    public int getCrtezId() {
        return this.crtezId;
    }
    
    public void setCrtezId(int crtezId) {
        this.crtezId = crtezId;
    }
    public int getKlasaId() {
        return this.klasaId;
    }
    
    public void setKlasaId(int klasaId) {
        this.klasaId = klasaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KlasnidId) ) return false;
		 KlasnidId castOther = ( KlasnidId ) other; 
         
		 return (this.getCrtezId()==castOther.getCrtezId())
 && (this.getKlasaId()==castOther.getKlasaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCrtezId();
         result = 37 * result + this.getKlasaId();
         return result;
   }   


}


