package store.entity;
// Generated Jan 9, 2018 4:38:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * KlasaDb generated by hbm2java
 */
public class KlasaDb  implements java.io.Serializable {


     private KlasaDbId id;
     private CrtezDb crtezDb;
     private Integer atributCounter;
     private Integer metodCounter;
     private Byte isAbstract;
     private Byte isStatic;
     private Set metodDbs = new HashSet(0);
     private Set atributDbs = new HashSet(0);

    public KlasaDb() {
    }

	
    public KlasaDb(KlasaDbId id, CrtezDb crtezDb) {
        this.id = id;
        this.crtezDb = crtezDb;
    }
    public KlasaDb(KlasaDbId id, CrtezDb crtezDb, Integer atributCounter, Integer metodCounter, Byte isAbstract, Byte isStatic, Set metodDbs, Set atributDbs) {
       this.id = id;
       this.crtezDb = crtezDb;
       this.atributCounter = atributCounter;
       this.metodCounter = metodCounter;
       this.isAbstract = isAbstract;
       this.isStatic = isStatic;
       this.metodDbs = metodDbs;
       this.atributDbs = atributDbs;
    }
   
    public KlasaDbId getId() {
        return this.id;
    }
    
    public void setId(KlasaDbId id) {
        this.id = id;
    }
    public CrtezDb getCrtezDb() {
        return this.crtezDb;
    }
    
    public void setCrtezDb(CrtezDb crtezDb) {
        this.crtezDb = crtezDb;
    }
    public Integer getAtributCounter() {
        return this.atributCounter;
    }
    
    public void setAtributCounter(Integer atributCounter) {
        this.atributCounter = atributCounter;
    }
    public Integer getMetodCounter() {
        return this.metodCounter;
    }
    
    public void setMetodCounter(Integer metodCounter) {
        this.metodCounter = metodCounter;
    }
    public Byte getIsAbstract() {
        return this.isAbstract;
    }
    
    public void setIsAbstract(Byte isAbstract) {
        this.isAbstract = isAbstract;
    }
    public Byte getIsStatic() {
        return this.isStatic;
    }
    
    public void setIsStatic(Byte isStatic) {
        this.isStatic = isStatic;
    }
    public Set getMetodDbs() {
        return this.metodDbs;
    }
    
    public void setMetodDbs(Set metodDbs) {
        this.metodDbs = metodDbs;
    }
    public Set getAtributDbs() {
        return this.atributDbs;
    }
    
    public void setAtributDbs(Set atributDbs) {
        this.atributDbs = atributDbs;
    }




}


