package store.entity;
// Generated Jan 9, 2018 4:38:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * KlasaDb generated by hbm2java
 */
public class KlasaDb  implements java.io.Serializable {


     private KlasaDbId id;
     private CrtezDb crtezDb;
     private Integer atributCounter;
     private Integer metodCounter;
     private String ime;
     private Boolean isAbstract;
     private Boolean isStatic;
     private Set atributDbs = new HashSet(0);

    public KlasaDb() {
    }

	
    public KlasaDb(KlasaDbId id, CrtezDb crtezDb) {
        this.id = id;
        this.crtezDb = crtezDb;
    }
    public KlasaDb(KlasaDbId id, CrtezDb crtezDb, Integer atributCounter, Integer metodCounter, Boolean isAbstract, Boolean isStatic, Set atributDbs) {
       this.id = id;
       this.crtezDb = crtezDb;
       this.atributCounter = atributCounter;
       this.metodCounter = metodCounter;
       this.isAbstract = isAbstract;
       this.isStatic = isStatic;
       this.atributDbs = atributDbs;
    }
   
    public KlasaDbId getId() {
        return this.id;
    }
    
    public void setId(KlasaDbId id) {
        this.id = id;
    }
    public CrtezDb getCrtezDb() {
        return this.crtezDb;
    }
    
    public void setCrtezDb(CrtezDb crtezDb) {
        this.crtezDb = crtezDb;
    }
    public Integer getAtributCounter() {
        return this.atributCounter;
    }
    
    public void setAtributCounter(Integer atributCounter) {
        this.atributCounter = atributCounter;
    }
    public Integer getMetodCounter() {
        return this.metodCounter;
    }
    
    public void setMetodCounter(Integer metodCounter) {
        this.metodCounter = metodCounter;
    }
    public Boolean getIsAbstract() {
        return this.isAbstract;
    }
    
    public void setIsAbstract(Boolean isAbstract) {
        this.isAbstract = isAbstract;
    }
    public Boolean getIsStatic() {
        return this.isStatic;
    }
    
    public void setIsStatic(Boolean isStatic) {
        this.isStatic = isStatic;
    }
   
    public Set getAtributDbs() {
        return this.atributDbs;
    }
    
    public void setAtributDbs(Set atributDbs) {
        this.atributDbs = atributDbs;
    }

    /**
     * @return the ime
     */
    public String getIme() {
        return ime;
    }

    /**
     * @param ime the ime to set
     */
    public void setIme(String ime) {
        this.ime = ime;
    }




}


