package store.entity;
// Generated Dec 27, 2017 1:33:44 AM by Hibernate Tools 4.3.1



/**
 * Konekcija generated by hbm2java
 */
public class Konekcija  implements java.io.Serializable {


     private Integer id;
     private Integer crtezId;
     private Integer uceCaseId;
     private Integer useCaseKonekcijaId;
     private String tipVeze;

    public Konekcija() {
    }

    public Konekcija(Integer crtezId, Integer uceCaseId, Integer useCaseKonekcijaId, String tipVeze) {
       this.crtezId = crtezId;
       this.uceCaseId = uceCaseId;
       this.useCaseKonekcijaId = useCaseKonekcijaId;
       this.tipVeze = tipVeze;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getCrtezId() {
        return this.crtezId;
    }
    
    public void setCrtezId(Integer crtezId) {
        this.crtezId = crtezId;
    }
    public Integer getUceCaseId() {
        return this.uceCaseId;
    }
    
    public void setUceCaseId(Integer uceCaseId) {
        this.uceCaseId = uceCaseId;
    }
    public Integer getUseCaseKonekcijaId() {
        return this.useCaseKonekcijaId;
    }
    
    public void setUseCaseKonekcijaId(Integer useCaseKonekcijaId) {
        this.useCaseKonekcijaId = useCaseKonekcijaId;
    }
    public String getTipVeze() {
        return this.tipVeze;
    }
    
    public void setTipVeze(String tipVeze) {
        this.tipVeze = tipVeze;
    }




}


