package store.entity;
// Generated Jan 3, 2018 7:59:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Korisnik generated by hbm2java
 */
public class Korisnik  implements java.io.Serializable {


     private String ime;
     private Crtez crtez;
     private String sifra;
     private Set crtezs = new HashSet(0);

    public Korisnik() {
    }

	
    public Korisnik(String ime) {
        this.ime = ime;
    }
    public Korisnik(String ime, Crtez crtez, String sifra, Set crtezs) {
       this.ime = ime;
       this.crtez = crtez;
       this.sifra = sifra;
       this.crtezs = crtezs;
    }
   
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public Crtez getCrtez() {
        return this.crtez;
    }
    
    public void setCrtez(Crtez crtez) {
        this.crtez = crtez;
    }
    public String getSifra() {
        return this.sifra;
    }
    
    public void setSifra(String sifra) {
        this.sifra = sifra;
    }
    public Set getCrtezs() {
        return this.crtezs;
    }
    
    public void setCrtezs(Set crtezs) {
        this.crtezs = crtezs;
    }




}


