package store.entity;
// Generated Jan 3, 2018 7:59:26 PM by Hibernate Tools 4.3.1



/**
 * MetodId generated by hbm2java
 */
public class MetodId  implements java.io.Serializable {


     private int crtezId;
     private int klasaIliInterfejsId;
     private int id;

    public MetodId() {
    }

    public MetodId(int crtezId, int klasaIliInterfejsId, int id) {
       this.crtezId = crtezId;
       this.klasaIliInterfejsId = klasaIliInterfejsId;
       this.id = id;
    }
   
    public int getCrtezId() {
        return this.crtezId;
    }
    
    public void setCrtezId(int crtezId) {
        this.crtezId = crtezId;
    }
    public int getKlasaIliInterfejsId() {
        return this.klasaIliInterfejsId;
    }
    
    public void setKlasaIliInterfejsId(int klasaIliInterfejsId) {
        this.klasaIliInterfejsId = klasaIliInterfejsId;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MetodId) ) return false;
		 MetodId castOther = ( MetodId ) other; 
         
		 return (this.getCrtezId()==castOther.getCrtezId())
 && (this.getKlasaIliInterfejsId()==castOther.getKlasaIliInterfejsId())
 && (this.getId()==castOther.getId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCrtezId();
         result = 37 * result + this.getKlasaIliInterfejsId();
         result = 37 * result + this.getId();
         return result;
   }   


}


