package store.entity;
// Generated Jan 9, 2018 4:38:35 PM by Hibernate Tools 4.3.1



/**
 * UseCaseKonekcijaDb generated by hbm2java
 */
public class UseCaseKonekcijaDb  implements java.io.Serializable {


     private UseCaseKonekcijaDbId id;
     private CrtezDb crtezDb;
     private int odKogaId;
     private int doKogaId;
     private String tipVeze;

    public UseCaseKonekcijaDb() {
    }

	
    public UseCaseKonekcijaDb(UseCaseKonekcijaDbId id, CrtezDb crtezDb, int odKogaId, int doKogaId) {
        this.id = id;
        this.crtezDb = crtezDb;
        this.odKogaId = odKogaId;
        this.doKogaId = doKogaId;
    }
    public UseCaseKonekcijaDb(UseCaseKonekcijaDbId id, CrtezDb crtezDb, int odKogaId, int doKogaId, String tipVeze) {
       this.id = id;
       this.crtezDb = crtezDb;
       this.odKogaId = odKogaId;
       this.doKogaId = doKogaId;
       this.tipVeze = tipVeze;
    }
   
    public UseCaseKonekcijaDbId getId() {
        return this.id;
    }
    
    public void setId(UseCaseKonekcijaDbId id) {
        this.id = id;
    }
    public CrtezDb getCrtezDb() {
        return this.crtezDb;
    }
    
    public void setCrtezDb(CrtezDb crtezDb) {
        this.crtezDb = crtezDb;
    }
    public int getOdKogaId() {
        return this.odKogaId;
    }
    
    public void setOdKogaId(int odKogaId) {
        this.odKogaId = odKogaId;
    }
    public int getDoKogaId() {
        return this.doKogaId;
    }
    
    public void setDoKogaId(int doKogaId) {
        this.doKogaId = doKogaId;
    }
    public String getTipVeze() {
        return this.tipVeze;
    }
    
    public void setTipVeze(String tipVeze) {
        this.tipVeze = tipVeze;
    }




}


