package store.entity;
// Generated Jan 3, 2018 7:59:26 PM by Hibernate Tools 4.3.1



/**
 * UseCaseKonekcija generated by hbm2java
 */
public class UseCaseKonekcija  implements java.io.Serializable {


     private UseCaseKonekcijaId id;
     private Crtez crtez;
     private UseCase useCaseByUseCaseConnOdKoga;
     private UseCase useCaseByUseCaseConnDoKoga;
     private String tipVeze;

    public UseCaseKonekcija() {
    }

	
    public UseCaseKonekcija(UseCaseKonekcijaId id, Crtez crtez, UseCase useCaseByUseCaseConnOdKoga, UseCase useCaseByUseCaseConnDoKoga) {
        this.id = id;
        this.crtez = crtez;
        this.useCaseByUseCaseConnOdKoga = useCaseByUseCaseConnOdKoga;
        this.useCaseByUseCaseConnDoKoga = useCaseByUseCaseConnDoKoga;
    }
    public UseCaseKonekcija(UseCaseKonekcijaId id, Crtez crtez, UseCase useCaseByUseCaseConnOdKoga, UseCase useCaseByUseCaseConnDoKoga, String tipVeze) {
       this.id = id;
       this.crtez = crtez;
       this.useCaseByUseCaseConnOdKoga = useCaseByUseCaseConnOdKoga;
       this.useCaseByUseCaseConnDoKoga = useCaseByUseCaseConnDoKoga;
       this.tipVeze = tipVeze;
    }
   
    public UseCaseKonekcijaId getId() {
        return this.id;
    }
    
    public void setId(UseCaseKonekcijaId id) {
        this.id = id;
    }
    public Crtez getCrtez() {
        return this.crtez;
    }
    
    public void setCrtez(Crtez crtez) {
        this.crtez = crtez;
    }
    public UseCase getUseCaseByUseCaseConnOdKoga() {
        return this.useCaseByUseCaseConnOdKoga;
    }
    
    public void setUseCaseByUseCaseConnOdKoga(UseCase useCaseByUseCaseConnOdKoga) {
        this.useCaseByUseCaseConnOdKoga = useCaseByUseCaseConnOdKoga;
    }
    public UseCase getUseCaseByUseCaseConnDoKoga() {
        return this.useCaseByUseCaseConnDoKoga;
    }
    
    public void setUseCaseByUseCaseConnDoKoga(UseCase useCaseByUseCaseConnDoKoga) {
        this.useCaseByUseCaseConnDoKoga = useCaseByUseCaseConnDoKoga;
    }
    public String getTipVeze() {
        return this.tipVeze;
    }
    
    public void setTipVeze(String tipVeze) {
        this.tipVeze = tipVeze;
    }




}


