package store.entity;
// Generated Jan 2, 2018 5:10:25 PM by Hibernate Tools 4.3.1



/**
 * UseCaseKonekcija generated by hbm2java
 */
public class UseCaseKonekcija  implements java.io.Serializable {


     private UseCaseKonekcijaId id;
     private Crtez crtez;
     private Integer uceCaseId;
     private Integer useCaseKonekcijaId;
     private String tipVeze;

    public UseCaseKonekcija() {
    }

	
    public UseCaseKonekcija(UseCaseKonekcijaId id, Crtez crtez) {
        this.id = id;
        this.crtez = crtez;
    }
    public UseCaseKonekcija(UseCaseKonekcijaId id, Crtez crtez, Integer uceCaseId, Integer useCaseKonekcijaId, String tipVeze) {
       this.id = id;
       this.crtez = crtez;
       this.uceCaseId = uceCaseId;
       this.useCaseKonekcijaId = useCaseKonekcijaId;
       this.tipVeze = tipVeze;
    }
   
    public UseCaseKonekcijaId getId() {
        return this.id;
    }
    
    public void setId(UseCaseKonekcijaId id) {
        this.id = id;
    }
    public Crtez getCrtez() {
        return this.crtez;
    }
    
    public void setCrtez(Crtez crtez) {
        this.crtez = crtez;
    }
    public Integer getUceCaseId() {
        return this.uceCaseId;
    }
    
    public void setUceCaseId(Integer uceCaseId) {
        this.uceCaseId = uceCaseId;
    }
    public Integer getUseCaseKonekcijaId() {
        return this.useCaseKonekcijaId;
    }
    
    public void setUseCaseKonekcijaId(Integer useCaseKonekcijaId) {
        this.useCaseKonekcijaId = useCaseKonekcijaId;
    }
    public String getTipVeze() {
        return this.tipVeze;
    }
    
    public void setTipVeze(String tipVeze) {
        this.tipVeze = tipVeze;
    }




}


