package store.entity;
// Generated Jan 3, 2018 7:59:26 PM by Hibernate Tools 4.3.1



/**
 * UseCaseId generated by hbm2java
 */
public class UseCaseId  implements java.io.Serializable {


     private int crtezId;
     private int id;

    public UseCaseId() {
    }

    public UseCaseId(int crtezId, int id) {
       this.crtezId = crtezId;
       this.id = id;
    }
   
    public int getCrtezId() {
        return this.crtezId;
    }
    
    public void setCrtezId(int crtezId) {
        this.crtezId = crtezId;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UseCaseId) ) return false;
		 UseCaseId castOther = ( UseCaseId ) other; 
         
		 return (this.getCrtezId()==castOther.getCrtezId())
 && (this.getId()==castOther.getId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCrtezId();
         result = 37 * result + this.getId();
         return result;
   }   


}


