/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package draw.mainApplication;

import communicationBroker.messages.LoginClient;
import communicationBroker.messages.LoginMessage;
import communicationBroker.messages.LoginResponse;
import communicationBroker.messages.MessageType;
import communicationBroker.messages.handleInterfaces.IHandleLoginResponse;
import draw.classDiagram.ClassDiagramApplicationModel;
import draw.commonClasses.UmlDrawSDIApplication;
import draw.usecase.UseCaseApplicationModel;
import javax.swing.JFrame;
import org.jhotdraw.app.Application;
import org.jhotdraw.app.DefaultSDIApplication;

/**
 *
 * @author Korisnik
 */
public class StartupApp extends javax.swing.JFrame implements IHandleLoginResponse {

    /**
     * Creates new form StartupApp
     */
    private LoginClient loginClient;
    
    public StartupApp() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        loginClient= new LoginClient(this);
        loginClient.startConsumer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DefaultPanel = new javax.swing.JPanel();
        btnStartUseCase = new javax.swing.JButton();
        btnStartClassDiagram = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        RegisterLoginPanel = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblSuccess = new javax.swing.JLabel();
        StartCrtezPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnStartUseCase.setText("Use Case Diagram");
        btnStartUseCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartUseCaseActionPerformed(evt);
            }
        });

        btnStartClassDiagram.setText("Class Diagram");
        btnStartClassDiagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartClassDiagramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DefaultPanelLayout = new javax.swing.GroupLayout(DefaultPanel);
        DefaultPanel.setLayout(DefaultPanelLayout);
        DefaultPanelLayout.setHorizontalGroup(
            DefaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DefaultPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(DefaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DefaultPanelLayout.createSequentialGroup()
                        .addComponent(btnStartClassDiagram, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DefaultPanelLayout.createSequentialGroup()
                        .addComponent(btnStartUseCase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(139, 139, 139))))
        );
        DefaultPanelLayout.setVerticalGroup(
            DefaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DefaultPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnStartUseCase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStartClassDiagram)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        MainPanel.setLayout(new java.awt.CardLayout());

        lblUsername.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblUsername.setText("Username:");

        lblPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPassword.setText("Password:");

        btnRegister.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblSuccess.setText("success indicator");

        javax.swing.GroupLayout RegisterLoginPanelLayout = new javax.swing.GroupLayout(RegisterLoginPanel);
        RegisterLoginPanel.setLayout(RegisterLoginPanelLayout);
        RegisterLoginPanelLayout.setHorizontalGroup(
            RegisterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLoginPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(RegisterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RegisterLoginPanelLayout.createSequentialGroup()
                        .addGroup(RegisterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegisterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addContainerGap(87, Short.MAX_VALUE))
                    .addGroup(RegisterLoginPanelLayout.createSequentialGroup()
                        .addComponent(btnRegister)
                        .addGap(63, 63, 63)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
            .addGroup(RegisterLoginPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(lblSuccess)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        RegisterLoginPanelLayout.setVerticalGroup(
            RegisterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLoginPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblSuccess)
                .addGap(50, 50, 50)
                .addGroup(RegisterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(RegisterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnLogin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(RegisterLoginPanel, "card2");

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout StartCrtezPanelLayout = new javax.swing.GroupLayout(StartCrtezPanel);
        StartCrtezPanel.setLayout(StartCrtezPanelLayout);
        StartCrtezPanelLayout.setHorizontalGroup(
            StartCrtezPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartCrtezPanelLayout.createSequentialGroup()
                .addGroup(StartCrtezPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StartCrtezPanelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButton1))
                    .addGroup(StartCrtezPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        StartCrtezPanelLayout.setVerticalGroup(
            StartCrtezPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartCrtezPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        MainPanel.add(StartCrtezPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DefaultPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DefaultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartUseCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartUseCaseActionPerformed
        //just fake command line arguments
        String[] args=null;
        
        Application app;
        String os = System.getProperty("os.name").toLowerCase();
        app = new UmlDrawSDIApplication();
        
        UseCaseApplicationModel model = new UseCaseApplicationModel();
        
        model.setName("UMLDraw u pokusaju");
        model.setVersion("0.5");
        model.setCopyright("Copyright IvanaMilivojevic");
        model.setProjectClassName("draw.usecase.UseCaseProject");
        app.setModel(model);
        app.launch(args);
    }//GEN-LAST:event_btnStartUseCaseActionPerformed

    private void btnStartClassDiagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartClassDiagramActionPerformed
         //just fake command line arguments
        String[] args=null;
        
        Application app;
        String os = System.getProperty("os.name").toLowerCase();
        app = new UmlDrawSDIApplication();
        
        ClassDiagramApplicationModel model = new ClassDiagramApplicationModel();
        
        model.setName("UMLDraw u pokusaju");
        model.setVersion("0.5");
        model.setCopyright("Copyright IvanaMilivojevic");
        model.setProjectClassName("draw.classDiagram.ClassDiagramProject");
        app.setModel(model);
        app.launch(args);
    }//GEN-LAST:event_btnStartClassDiagramActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        String[] credentials= new String[2];
        credentials[0]=txtUsername.getText();
        credentials[1]=txtPassword.getText();
        
        LoginMessage message= new LoginMessage();
        message.setMessageType(MessageType.LOGIN);
        message.setPayload(credentials);
        
        loginClient.sendLoginMessage(message);
        setEnableLoginButtons(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String[] credentials= new String[2];
        credentials[0]=txtUsername.getText();
        credentials[1]=txtPassword.getText();
        
        LoginMessage message= new LoginMessage();
        message.setMessageType(MessageType.REGISTER);
        message.setPayload(credentials);
        
        loginClient.sendLoginMessage(message);
        setEnableLoginButtons(false);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        loginClient.stopConsumer();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartupApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartupApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartupApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartupApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartupApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DefaultPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel RegisterLoginPanel;
    private javax.swing.JPanel StartCrtezPanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnStartClassDiagram;
    private javax.swing.JButton btnStartUseCase;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSuccess;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    @Override
    public void HandleLoginResponse(LoginResponse response) {
        switch(response.getResponseType()){
            case MessageType.LOGIN_RESPONSE:
            {
                boolean success= (boolean)response.getPayload();
                if(success)
                    lblSuccess.setText("Logging successfull!");
                else
                    lblSuccess.setText("Logging failed!");
                
                setEnableLoginButtons(true);
                break;
            }
            case MessageType.REGISTER_RESPONSE:
            {
                boolean success= (boolean)response.getPayload();
                if(success)
                    lblSuccess.setText("Registration successfull!");
                else
                    lblSuccess.setText("Registration failed!");
                
                setEnableLoginButtons(true);
                break;
            }
        }
    }
    
    private void setEnableLoginButtons(boolean enable)
    {
        btnLogin.setEnabled(enable);
        btnRegister.setEnabled(enable);
    }
}
