/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package draw.mainApplication;

import draw.classDiagram.ClassDiagramApplicationModel;
import draw.usecase.UseCaseApplicationModel;
import javax.swing.JFrame;
import org.jhotdraw.app.Application;
import org.jhotdraw.app.DefaultSDIApplication;

/**
 *
 * @author Korisnik
 */
public class StartupApp extends javax.swing.JFrame {

    /**
     * Creates new form StartupApp
     */
    public StartupApp() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStartUseCase = new javax.swing.JButton();
        btnStartClassDiagram = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStartUseCase.setText("Use Case Diagram");
        btnStartUseCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartUseCaseActionPerformed(evt);
            }
        });

        btnStartClassDiagram.setText("Class Diagram");
        btnStartClassDiagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartClassDiagramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStartUseCase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStartClassDiagram, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btnStartUseCase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStartClassDiagram)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartUseCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartUseCaseActionPerformed
        //just fake command line arguments
        String[] args=null;
        
        Application app;
        String os = System.getProperty("os.name").toLowerCase();
        app = new DefaultSDIApplication();
        
        UseCaseApplicationModel model = new UseCaseApplicationModel();
        
        model.setName("UMLDraw u pokusaju");
        model.setVersion("0.5");
        model.setCopyright("Copyright IvanaMilivojevic");
        model.setProjectClassName("draw.usecase.UseCaseProject");
        app.setModel(model);
        app.launch(args);
    }//GEN-LAST:event_btnStartUseCaseActionPerformed

    private void btnStartClassDiagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartClassDiagramActionPerformed
         //just fake command line arguments
        String[] args=null;
        
        Application app;
        String os = System.getProperty("os.name").toLowerCase();
        app = new DefaultSDIApplication();
        
        ClassDiagramApplicationModel model = new ClassDiagramApplicationModel();
        
        model.setName("UMLDraw u pokusaju");
        model.setVersion("0.5");
        model.setCopyright("Copyright IvanaMilivojevic");
        model.setProjectClassName("draw.classDiagram.ClassDiagramProject");
        app.setModel(model);
        app.launch(args);
    }//GEN-LAST:event_btnStartClassDiagramActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartupApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartupApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartupApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartupApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartupApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartClassDiagram;
    private javax.swing.JButton btnStartUseCase;
    // End of variables declaration//GEN-END:variables
}
